-- booleanexpression.expression

DROP TRIGGER booleanexpression_expression_clob_before_insert_trigger ON booleanexpression;
DROP FUNCTION booleanexpression_expression_clob_before_insert();

DROP TRIGGER booleanexpression_expression_clob_before_update_trigger ON booleanexpression;
DROP FUNCTION booleanexpression_expression_clob_before_update();

DROP TRIGGER booleanexpression_expression_clob_after_update_trigger ON booleanexpression;
DROP FUNCTION booleanexpression_expression_clob_after_update();

DROP TRIGGER booleanexpression_expression_clob_after_delete_trigger ON booleanexpression;
DROP FUNCTION booleanexpression_expression_clob_after_delete();

-- email_header.body

DROP TRIGGER email_header_body_clob_before_insert_trigger ON email_header;
DROP FUNCTION email_header_body_clob_before_insert();

DROP TRIGGER email_header_body_clob_before_update_trigger ON email_header;
DROP FUNCTION email_header_body_clob_before_update();

DROP TRIGGER email_header_body_clob_after_update_trigger ON email_header;
DROP FUNCTION email_header_body_clob_after_update();

DROP TRIGGER email_header_body_clob_after_delete_trigger ON email_header;
DROP FUNCTION email_header_body_clob_after_delete();

-- i18ntext.text

DROP TRIGGER i18ntext_text_clob_before_insert_trigger ON i18ntext;
DROP FUNCTION i18ntext_text_clob_before_insert();

DROP TRIGGER i18ntext_text_clob_before_update_trigger ON i18ntext;
DROP FUNCTION i18ntext_text_clob_before_update();

DROP TRIGGER i18ntext_text_clob_after_update_trigger ON i18ntext;
DROP FUNCTION i18ntext_text_clob_after_update();

DROP TRIGGER i18ntext_text_clob_after_delete_trigger ON i18ntext;
DROP FUNCTION i18ntext_text_clob_after_delete();

-- task_comment.text

DROP TRIGGER task_comment_text_clob_before_insert_trigger ON task_comment;
DROP FUNCTION task_comment_text_clob_before_insert();

DROP TRIGGER task_comment_text_clob_before_update_trigger ON task_comment;
DROP FUNCTION task_comment_text_clob_before_update();

DROP TRIGGER task_comment_text_clob_after_update_trigger ON task_comment;
DROP FUNCTION task_comment_text_clob_after_update();

DROP TRIGGER task_comment_text_clob_after_delete_trigger ON task_comment;
DROP FUNCTION task_comment_text_clob_after_delete();

-- querydefinitionstore.qexpression

DROP TRIGGER querydefinitionstore_qexpression_clob_before_insert_trigger ON querydefinitionstore;
DROP FUNCTION querydefinitionstore_qexpression_clob_before_insert();

DROP TRIGGER querydefinitionstore_qexpression_clob_before_update_trigger ON querydefinitionstore;
DROP FUNCTION querydefinitionstore_qexpression_clob_before_update();

DROP TRIGGER querydefinitionstore_qexpression_clob_after_update_trigger ON querydefinitionstore;
DROP FUNCTION querydefinitionstore_qexpression_clob_after_update();

DROP TRIGGER querydefinitionstore_qexpression_clob_after_delete_trigger ON querydefinitionstore;
DROP FUNCTION querydefinitionstore_qexpression_clob_after_delete();

-- deploymentstore.deploymentunit

DROP TRIGGER deploymentstore_deploymentunit_clob_before_insert_trigger ON deploymentstore;
DROP FUNCTION deploymentstore_deploymentunit_clob_before_insert();

DROP TRIGGER deploymentstore_deploymentunit_clob_before_update_trigger ON deploymentstore;
DROP FUNCTION deploymentstore_deploymentunit_clob_before_update();

DROP TRIGGER deploymentstore_deploymentunit_clob_after_update_trigger ON deploymentstore;
DROP FUNCTION deploymentstore_deploymentunit_clob_after_update();

DROP TRIGGER deploymentstore_deploymentunit_clob_after_delete_trigger ON deploymentstore;
DROP FUNCTION deploymentstore_deploymentunit_clob_after_delete();

